<!DOCTYPE html>
<html lang="en"><meta charset="utf-8"><meta name="generator" content="Hugo 0.86.1" /><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="light dark">
<meta name="supported-color-schemes" content="light dark"><title>Python面向对象-14-异常&nbsp;&ndash;&nbsp;Wei Chu</title><link rel="stylesheet" href="/css/core.min.746d4f5e0f69f8ca3fdabdfef6b99d63a9852de221102d14b47177e2a4e0fb979941c84b1ae5b6a490e592140624482e.css" integrity="sha384-dG1PXg9p&#43;Mo/2r3&#43;9rmdY6mFLeIhEC0UtHF34qTg&#43;5eZQchLGuW2pJDlkhQGJEgu"><body>
    <div class="base-body"><section id="header" class="site header">
    <div class="header wrap"><span class="header left-side"><a class="site home" href="/"><img class="site logo" src="/images/logo.png" alt /><span class="site name">Wei Chu</span></a></span>
        <span class="header right-side"><div class="nav wrap"><nav class="nav"><a class="nav item" href="/categories/">Categories</a><a class="nav item" href="/tags/">Tags</a><a class="nav item" href="/about/">About</a><a class="nav item" href="https://gohugo.io/"target="_blank">Hugo</a></nav></div></span></div><div class="site slogan"><span class="title">醉后不知天在水 满船清梦压星河</span></div></section><div id="content"><section class="article header">
    <h1 class="article title">Python面向对象-14-异常</h1><p class="article date">Oct 22, 2021<span class="reading-time"> • 4 minutes to read</span></p></section><article class="article markdown-body"><h1 id="异常">异常</h1>
<h2 id="目标">目标</h2>
<ul>
<li>异常的概念</li>
<li>捕获异常</li>
<li>异常的传递</li>
<li>抛出异常</li>
</ul>
<h2 id="01-异常的概念">01. 异常的概念</h2>
<ul>
<li>程序在运行时，如果 <code>Python 解释器</code> <strong>遇到</strong> 到一个错误，<strong>会停止程序的执行，并且提示一些错误信息</strong>，这就是 <strong>异常</strong></li>
<li><strong>程序停止执行并且提示错误信息</strong> 这个动作，我们通常称之为：<strong>抛出(raise)异常</strong></li>
</ul>
<p><a target="_blank" rel="noopener noreferrer" 
  href="media/14989636063700/001_%E5%BC%82%E5%B8%B8%E7%A4%BA%E6%84%8F%E5%9B%BE.png"><img  src="media/14989636063700/001_%E5%BC%82%E5%B8%B8%E7%A4%BA%E6%84%8F%E5%9B%BE.png"
        alt="001_异常示意图-w480"/></a></p>
<blockquote>
<p>程序开发时，很难将 <strong>所有的特殊情况</strong> 都处理的面面俱到，通过 <strong>异常捕获</strong> 可以针对突发事件做集中的处理，从而保证程序的 <strong>稳定性和健壮性</strong></p>
</blockquote>
<h2 id="02-捕获异常">02. 捕获异常</h2>
<h3 id="21-简单的捕获异常语法">2.1 简单的捕获异常语法</h3>
<ul>
<li>在程序开发中，如果 <strong>对某些代码的执行不能确定是否正确</strong>，可以增加 <code>try(尝试)</code> 来 <strong>捕获异常</strong></li>
<li>捕获异常最简单的语法格式：</li>
</ul>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="n">尝试执行的代码</span>
<span class="k">except</span><span class="p">:</span>
    <span class="n">出现错误的处理</span>
</code></pre></div><ul>
<li><code>try</code> <strong>尝试</strong>，下方编写要尝试代码，不确定是否能够正常执行的代码</li>
<li><code>except</code> <strong>如果不是</strong>，下方编写尝试失败的代码</li>
</ul>
<h4 id="简单异常捕获演练--要求用户输入整数">简单异常捕获演练 —— 要求用户输入整数</h4>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="c1"># 提示用户输入一个数字</span>
    <span class="n">num</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&#34;请输入数字：&#34;</span><span class="p">))</span>
<span class="k">except</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;请输入正确的数字&#34;</span><span class="p">)</span>
</code></pre></div><h3 id="22-错误类型捕获">2.2 错误类型捕获</h3>
<ul>
<li>
<p>在程序执行时，可能会遇到 <strong>不同类型的异常</strong>，并且需要 <strong>针对不同类型的异常，做出不同的响应</strong>，这个时候，就需要捕获错误类型了</p>
</li>
<li>
<p>语法如下：</p>
</li>
</ul>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="c1"># 尝试执行的代码</span>
    <span class="k">pass</span>
<span class="k">except</span> <span class="n">错误类型1</span><span class="p">:</span>
    <span class="c1"># 针对错误类型1，对应的代码处理</span>
    <span class="k">pass</span>
<span class="k">except</span> <span class="p">(</span><span class="n">错误类型2</span><span class="p">,</span> <span class="n">错误类型3</span><span class="p">):</span>
    <span class="c1"># 针对错误类型2 和 3，对应的代码处理</span>
    <span class="k">pass</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">result</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;未知错误 </span><span class="si">%s</span><span class="s2">&#34;</span> <span class="o">%</span> <span class="n">result</span><span class="p">)</span>
</code></pre></div><ul>
<li>当 <code>Python</code> 解释器 <strong>抛出异常</strong> 时，<strong>最后一行错误信息的第一个单词，就是错误类型</strong></li>
</ul>
<h4 id="异常类型捕获演练--要求用户输入整数">异常类型捕获演练 —— 要求用户输入整数</h4>
<p><strong>需求</strong></p>
<ol>
<li>提示用户输入一个整数</li>
<li>使用 <code>8</code> 除以用户输入的整数并且输出</li>
</ol>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="n">num</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&#34;请输入整数：&#34;</span><span class="p">))</span>
    <span class="n">result</span> <span class="o">=</span> <span class="mi">8</span> <span class="o">/</span> <span class="n">num</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">result</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;请输入正确的整数&#34;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;除 0 错误&#34;</span><span class="p">)</span>

</code></pre></div><h4 id="捕获未知错误">捕获未知错误</h4>
<ul>
<li>在开发时，<strong>要预判到所有可能出现的错误</strong>，还是有一定难度的</li>
<li>如果希望程序 <strong>无论出现任何错误</strong>，都不会因为 <code>Python</code> 解释器 <strong>抛出异常而被终止</strong>，可以再增加一个 <code>except</code></li>
</ul>
<p>语法如下：</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">result</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;未知错误 </span><span class="si">%s</span><span class="s2">&#34;</span> <span class="o">%</span> <span class="n">result</span><span class="p">)</span>
</code></pre></div><h3 id="23-异常捕获完整语法">2.3 异常捕获完整语法</h3>
<ul>
<li>在实际开发中，为了能够处理复杂的异常情况，完整的异常语法如下：</li>
</ul>
<blockquote>
<p>提示：</p>
<ul>
<li>有关完整语法的应用场景，在后续学习中，<strong>结合实际的案例</strong>会更好理解</li>
<li>现在先对这个语法结构有个印象即可</li>
</ul>
</blockquote>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="c1"># 尝试执行的代码</span>
    <span class="k">pass</span>
<span class="k">except</span> <span class="n">错误类型1</span><span class="p">:</span>
    <span class="c1"># 针对错误类型1，对应的代码处理</span>
    <span class="k">pass</span>
<span class="k">except</span> <span class="n">错误类型2</span><span class="p">:</span>
    <span class="c1"># 针对错误类型2，对应的代码处理</span>
    <span class="k">pass</span>
<span class="k">except</span> <span class="p">(</span><span class="n">错误类型3</span><span class="p">,</span> <span class="n">错误类型4</span><span class="p">):</span>
    <span class="c1"># 针对错误类型3 和 4，对应的代码处理</span>
    <span class="k">pass</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">result</span><span class="p">:</span>
    <span class="c1"># 打印错误信息</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">result</span><span class="p">)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="c1"># 没有异常才会执行的代码</span>
    <span class="k">pass</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="c1"># 无论是否有异常，都会执行的代码</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;无论是否有异常，都会执行的代码&#34;</span><span class="p">)</span>
</code></pre></div><ul>
<li>
<p><code>else</code> 只有在没有异常时才会执行的代码</p>
</li>
<li>
<p><code>finally</code> 无论是否有异常，都会执行的代码</p>
</li>
<li>
<p>之前一个演练的 <strong>完整捕获异常</strong> 的代码如下：</p>
</li>
</ul>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="n">num</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&#34;请输入整数：&#34;</span><span class="p">))</span>
    <span class="n">result</span> <span class="o">=</span> <span class="mi">8</span> <span class="o">/</span> <span class="n">num</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">result</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;请输入正确的整数&#34;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;除 0 错误&#34;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">result</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;未知错误 </span><span class="si">%s</span><span class="s2">&#34;</span> <span class="o">%</span> <span class="n">result</span><span class="p">)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;正常执行&#34;</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;执行完成，但是不保证正确&#34;</span><span class="p">)</span>

</code></pre></div><h2 id="03-异常的传递">03. 异常的传递</h2>
<ul>
<li><strong>异常的传递</strong> —— 当 <strong>函数/方法</strong> 执行 <strong>出现异常</strong>，会 <strong>将异常传递</strong> 给 函数/方法 的 <strong>调用一方</strong></li>
<li>如果 <strong>传递到主程序</strong>，仍然 <strong>没有异常处理</strong>，程序才会被终止</li>
</ul>
<blockquote>
<p>提示</p>
</blockquote>
<ul>
<li>在开发中，可以在主函数中增加 <strong>异常捕获</strong></li>
<li>而在主函数中调用的其他函数，只要出现异常，都会传递到主函数的 <strong>异常捕获</strong> 中</li>
<li>这样就不需要在代码中，增加大量的 <strong>异常捕获</strong>，能够保证代码的整洁</li>
</ul>
<p><strong>需求</strong></p>
<ol>
<li>定义函数 <code>demo1()</code> <strong>提示用户输入一个整数并且返回</strong></li>
<li>定义函数 <code>demo2()</code> 调用 <code>demo1()</code></li>
<li>在主程序中调用 <code>demo2()</code></li>
</ol>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="k">def</span> <span class="nf">demo1</span><span class="p">():</span>
    <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&#34;请输入一个整数：&#34;</span><span class="p">))</span>


<span class="k">def</span> <span class="nf">demo2</span><span class="p">():</span>
    <span class="k">return</span> <span class="n">demo1</span><span class="p">()</span>

<span class="k">try</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">demo2</span><span class="p">())</span>
<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;请输入正确的整数&#34;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">result</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;未知错误 </span><span class="si">%s</span><span class="s2">&#34;</span> <span class="o">%</span> <span class="n">result</span><span class="p">)</span>

</code></pre></div><h2 id="04-抛出-raise-异常">04. 抛出 <code>raise</code> 异常</h2>
<h3 id="41-应用场景">4.1 应用场景</h3>
<ul>
<li>在开发中，除了 <strong>代码执行出错</strong> <code>Python</code> 解释器会 <strong>抛出</strong> 异常之外</li>
<li>还可以根据 <strong>应用程序</strong> <strong>特有的业务需求</strong> <strong>主动抛出异常</strong></li>
</ul>
<p><strong>示例</strong></p>
<ul>
<li>提示用户 <strong>输入密码</strong>，如果 <strong>长度少于 8</strong>，抛出 <strong>异常</strong></li>
</ul>
<p><a target="_blank" rel="noopener noreferrer" 
  href="media/15016413521006/024_%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8.png"><img  src="media/15016413521006/024_%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8.png"
        alt="024_自定义异常-w822"/></a></p>
<p><strong>注意</strong></p>
<ul>
<li>当前函数 <strong>只负责</strong> 提示用户输入密码，如果 <strong>密码长度不正确，需要其他的函数进行额外处理</strong></li>
<li>因此可以 <strong>抛出异常</strong>，由其他需要处理的函数 <strong>捕获异常</strong></li>
</ul>
<h3 id="42-抛出异常">4.2 抛出异常</h3>
<ul>
<li><code>Python</code> 中提供了一个 <code>Exception</code> <strong>异常类</strong></li>
<li>在开发时，如果满足 <strong>特定业务需求时</strong>，希望 <strong>抛出异常</strong>，可以：
<ol>
<li><strong>创建</strong> 一个 <code>Exception</code> 的 <strong>对象</strong></li>
<li>使用 <code>raise</code> <strong>关键字</strong> 抛出 <strong>异常对象</strong></li>
</ol>
</li>
</ul>
<p><strong>需求</strong></p>
<ul>
<li>定义 <code>input_password</code> 函数，提示用户输入密码</li>
<li>如果用户输入长度 &lt; 8，抛出异常</li>
<li>如果用户输入长度 &gt;=8，返回输入的密码</li>
</ul>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="k">def</span> <span class="nf">input_password</span><span class="p">():</span>

    <span class="c1"># 1. 提示用户输入密码</span>
    <span class="n">pwd</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s2">&#34;请输入密码：&#34;</span><span class="p">)</span>

    <span class="c1"># 2. 判断密码长度，如果长度 &gt;= 8，返回用户输入的密码</span>
    <span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="n">pwd</span><span class="p">)</span> <span class="o">&gt;=</span> <span class="mi">8</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">pwd</span>

    <span class="c1"># 3. 密码长度不够，需要抛出异常</span>
    <span class="c1"># 1&gt; 创建异常对象 - 使用异常的错误信息字符串作为参数</span>
    <span class="n">ex</span> <span class="o">=</span> <span class="ne">Exception</span><span class="p">(</span><span class="s2">&#34;密码长度不够&#34;</span><span class="p">)</span>

    <span class="c1"># 2&gt; 抛出异常对象</span>
    <span class="k">raise</span> <span class="n">ex</span>


<span class="k">try</span><span class="p">:</span>
    <span class="n">user_pwd</span> <span class="o">=</span> <span class="n">input_password</span><span class="p">()</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">user_pwd</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">result</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;发现错误：</span><span class="si">%s</span><span class="s2">&#34;</span> <span class="o">%</span> <span class="n">result</span><span class="p">)</span>

</code></pre></div></article><section class="article labels"><a class="category" href=/categories/python%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1/>Python面向对象</a><a class="tag" href=/tags/%E5%BC%82%E5%B8%B8/>异常</a></section><section class="article navigation"><p><a class="link" href="/post/python%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1-13_%E6%96%87%E4%BB%B6/"><span class="li">&larr;</span>Python面向对象-13-文件</a></p><p><a class="link" href="/post/%E4%BA%B2%E5%AF%86%E5%85%B3%E7%B3%BB-%E7%AC%AC%E4%BA%8C%E7%AB%A0%E7%A0%94%E7%A9%B6%E6%96%B9%E6%B3%95/"><span class="li">&rarr;</span>亲密关系-第二章：研究方法</a class="link">
    </p></section></div><section id="footer" class="footer">
    <script src="https://utteranc.es/client.js"
        repo="ChuWeiEr/hugoblogtalks"
        issue-term="pathname"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script><div class="footer-wrap">
    <p class="copyright">©2020 Notepadium.</p>
    <p class="powerby"><span>Powered by </span><a href="https://gohugo.io" 
        target="_blank">Hugo</a><span> and the </span><a href="https://themes.gohugo.io/hugo-notepadium/" 
        target="_blank">Notepadium</a></p>
</div></section><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" integrity="sha384-zB1R0rpPzHqg7Kpt0Aljp8JPLqbXI3bhnPWROx27a9N0Ll6ZP/&#43;DiW/UqRcLbRjq" crossorigin="anonymous"><script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js" integrity="sha384-y23I5Q6l&#43;B6vatafAwxRu/0oK/79VlbSz7Q9aiSZUvyWYIYsd&#43;qj&#43;o24G5ZU2zJz" crossorigin="anonymous"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous"
            onload="renderMathInElement(document.body);"></script></div>
</body>

</html>